### ISSUE TITLE
Can we run dorylus without ec2man?

### ISSUE THREAD

**Issue by yuxineverforever** [uclasystem/dorylus#4]
Hey authors, @kevalvora @ivanium @josehu07 @redhairdragon @johnnt849 
Thank you for making dorylus open-sourced and write this detailed wiki!

I am wondering if it is possible to run `dorylus` without using ec2man? Basically I launch some instances on AWS, and compile `weightserver` and `graphserver` into binary files and directly run on that. Is that possible? 

Also for the [build--upload-lambda-functions](https://github.com/uclasystem/dorylus/wiki/4.-Setup-Lambda-Functions#build--upload-lambda-functions), I cannot find the example `forward-prop-josehu`, can you give me a pointer for that?

Do I need to strictly follow the instance required here for CPU/GPU backend? Can I launch other type of instance?
```
    For the serverless based backend: ami-07aec0eb32327b38d
    For the CPU based backend: ami-04934e5a63d144d88
    For the GPU based backend: ami-01c390943eecea45c
    For the Weight Server: ami-0901fc9a7bc310a8a
```
Thanks!

**Comment by ivanium** [comment]
Hi,

Thank you for trying Dorylus. Here are my answers to your questions:

> Is it possible to run without using `ec2man`?

Yes, you can. `ec2man` is only a helper module to ease managing and accessing instances. You can still refer to scripts under the `run` directory, and replace all `ec2man` related commands with ssh commands to access the corresponding instance.

> I cannot find the example `forward-prop-josehu`.

Sorry the document is outdated. Please refer to `src/funcs/gcn` as an example.

> Instances and AMIs for CPU/GPU backend.

You can choose other instance types. One know issue is that the lambda function should **not** be compiled on a compute-optimized instance (i.e., do **not** use C-series instances). I recommend using a t3.medium instance to compile and upload the lambda function.
Those AMIs you posted are just some pre-configured images with drivers and binaries installed. Feel free to create your own image and set up the environment.



Hope this helps, and good luck!
